sudo: required

services:
  - docker

before_install:
  - mkdir -p output/pdf
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -d -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor **/*.adoc -D /documents/output
  - docker run -d -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf **/*.adoc -D /documents/output/pdf

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  
after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf
  
after_success:
  - docker logs asciidoc-to-pdf ; docker logs asciidoc-to-html
  - cd output ; git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1